### ISSUE TITLE
Excluded file still processed if explicitly passed

### ISSUE THREAD

**Issue by wpenton-itc** [designsecurity/progpilot#28]
If you add a file to the "exclude_files" section of a configuration file but then pass that file to be processed the file is still processed instead of being excluded.

My case:
I have a VERY large project and for some reason there are a few files within the project that causes Progpilot to crash. For now I want to exclude those files to be able to still process everything else. My issue is that I am doing a diff between my current working branch to the master branch to get a list of files that have been changed, then pass those filenames to progpilot to be processed. Mind you this way saves processing time but it still takes over 30 minutes to run, as opposed to 3-4 hours (I told you it was a large project).

**Comment by eric-therond** [comment]
Hi @wpenton-itc 
about performances problems, it's a lot of work, I plan to do something at the end of the year.

Normally excluded files/folders should not be analyzed.
Can you share your `exclude_files` configuration? and the project structure?

Eric

**Comment by eric-therond** [comment]
How to you run progpilot?
```
progpilot --configuration configuration.yml /usr/www/trunck/
```

I forgot to ask, in the configuration file what are the values for:
- `setFolder`
- `setFile`
- `setIncludes`

Eric

**Comment by wpenton-itc** [comment]
full configuration.yml file

```
inputs:
  setDev: false
  setLanguages:
    - php
  setFrameworks:
    - laravel
  setSources: ~
  setSinks: ~
  setValidators: ~
  setSanitizers: ~
  setCustomRules: ~
  setIncludes: ~
  setExcludes:
  exclude_files:
    - "/usr/www/trunk/.blackfire.yml"
    - "/usr/www/trunk/.dockerignore"
    - "/usr/www/trunk/.editorconfig"
    - "/usr/www/trunk/.env"
    - "/usr/www/trunk/.env.example"
    - "/usr/www/trunk/.env.testing"
    - "/usr/www/trunk/.env.trunk"
    - "/usr/www/trunk/.php_cs.dist"
    - "/usr/www/trunk/.psysh.php"
    - "/usr/www/trunk/.artifactignore"
    - "/usr/www/trunk/.phpstorm.meta.php"
    - "/usr/www/trunk/c3.php"
    - "/usr/www/trunk/app/Providers/FakerServiceProvider.php"
    - "/usr/www/trunk/customerPost.php"
    - "/usr/www/trunk/Classes/DropdownClass.php"
  exclude_folders:
    - "/usr/www/trunk/.git"
    - "/usr/www/trunk/.internal"
    - "/usr/www/trunk/vendor"
    - "/usr/www/trunk/node_modules"
    - "/usr/www/trunk/.sass-cache"
    - "/usr/www/trunk/.idea"
  setFile: ~
  setCode: ~
  setResolvedIncludes: ~
  setFalsePositives: ~

outputs:
  taintedFlow: false
  resolveIncludes: false
  resolveIncludesFile: ~

options:
  setAnalyzeIncludes: true
  setAnalyzeFunctions: true
  setAnalyzeHardRules: true
  setPrintFile: true
  setPrintWarning: false
  setPrettyPrint: true
  setLimitTime: 10
  setLimitDefs: 3000
  setLimitSize: 500000
```
